### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by unaizalakain** [GISAElkartea/amv2#118]

**Comment by iunetrecet** [comment]
In small and medium version, put the radio in the first place

**Comment by iunetrecet** [comment]
Look for a smarter way for the nav in a small screen

**Comment by iunetrecet** [comment]
In the radio list, responsive is not working

**Comment by iunetrecet** [comment]
Mobile responsive?

**Comment by iunetrecet** [comment]
Ez dakite zergatik, chromen media querieak ez dira tamainu txikiak ondo hartzen

**Comment by iunetrecet** [comment]
The aside from the news and radio section should go before main content

**Comment by iunetrecet** [comment]
Ikusi ere nola gelditzen den DFPa $smallen
