### ISSUE TITLE
License visibility?

### ISSUE THREAD

**Issue by unaizalakain** [GISAElkartea/amv2#120]

**Comment by iunetrecet** [comment]
What license?

**Comment by unaizalakain** [comment]
I think (we have it written down somewhere) we said that the new website should have clearer license notices.

Right now, every blob (audio files) has a related license (which consists of a name and a link). Are we going to do something with those licenses? Do I remove the model? Are the licenses supposed to be per blob or per podcast? If the licenses are per blob, how are we going to display the several licenses the blobs of a news will have?

**Comment by unaizalakain** [comment]
Also, related: https://github.com/GISAElkartea/amv2/issues/64

**Comment by iunetrecet** [comment]
And if we display the license in the player?

**Comment by unaizalakain** [comment]
The only possible problem with that is that the user may directly 
download a blob without adding it to the playlist and therefore without 
seeing its license.

**Comment by iunetrecet** [comment]
Oh ok! But we don't display any blob list anywhere.
