### ISSUE TITLE
Past and future occurrences are not appearing well in the event detail

### ISSUE THREAD

**Issue by iunetrecet** [GISAElkartea/amv2#125]

**Comment by unaizalakain** [comment]
It's going to be impossible to display past occurrences until python-dateutil
solves #15. What's exactly the problem with the future dates?

**Comment by iunetrecet** [comment]
![occurrences](https://cloud.githubusercontent.com/assets/2520681/9527984/9c7881e8-4cf2-11e5-8d7d-79b1403ed68f.jpg)
This is the problem

**Comment by unaizalakain** [comment]
I removed the past occurrences for the meantime. I also removed the `Future occurrences` title as we only have future occurrences. Maybe it was a mistake to remove it though, some short explanation like `Occurrences` would be advisable; feel free to add it back.

Anyway, future occurrences are now correctly sliced.
