### ISSUE TITLE
Some few improvements in the radio podcast descriptions

### ISSUE THREAD

**Issue by unaizalakain** [GISAElkartea/amv2#126]
- cursor change when over the podcast (title or date)
- open the description when clicking on the date too
- close the description when clicking on the title or date

**Comment by iunetrecet** [comment]
I don't know if this is the best way of doing the podcast list, we should look for another way and I think that it would be with JS.

**Comment by unaizalakain** [comment]
Yes, it may be the best way. I'll look into it.

**Comment by iunetrecet** [comment]
We can use the bourbon refills first accordion

**Comment by iunetrecet** [comment]
The same problem in the project podcasts

**Comment by unaizalakain** [comment]
I added a tiny js library (`js/folder.js`) that folds and unfolds elements based on a click on a parent element. To use it, just include the library and add the corresponding classes:

```
<div class="folder">
  When you click on this, the display of the child element with `folderContent` will be toggled.
  <div class="folderContent">This will be toggled</div>
</div>
```

You can find an example on the radio podcast list template. Please, also use this library for the project podcast folding.

**Comment by unaizalakain** [comment]
I added a tiny js library (`js/folder.js`) that folds and unfolds elements based on a click on a parent element. To use it, just include the library and add the corresponding classes:

```
<div class="folder">
  When you click on this, the display of the child element with `folderContent` will be toggled.
  <div class="folderContent">This will be toggled</div>
</div>
```

You can find an example on the radio podcast list template. Please, also use this library for the project podcast folding.

**Comment by unaizalakain** [comment]
I added a tiny js library (`js/folder.js`) that folds and unfolds elements based on a click on a parent element. To use it, just include the library and add the corresponding classes:

```
<div class="folder">
  When you click on this, the display of the child element with `folderContent` will be toggled.
  <div class="folderContent">This will be toggled</div>
</div>
```

You can find an example on the radio podcast list template. Please, also use this library for the project podcast folding.
