### ISSUE TITLE
Better tabs

### ISSUE THREAD

**Issue by iunetrecet** [GISAElkartea/amv2#128]

**Comment by unaizalakain** [comment]
The tabs example on that page needs javascript to work. I don't say we 
should not use it but what is the advantage over the current css-only 
implementation?

**Comment by iunetrecet** [comment]
I can not make the tab content fix well to the page

**Comment by unaizalakain** [comment]
As far as I understood:

We have a series of tab selectors, each with an unique identifier.
We have a series of tab content boxes, each of them tied uniquelly to a tab selector.
When a tab selector is clicked, we want to hide all tab contents but the one with the same unique identifier than the selected tab.

Is that what we want @iunetrecet? It shouldn't be too difficult to write some js that does it.

**Comment by unaizalakain** [comment]
I added a small library for managing tabs. You can find an example use case in the archive search template. In short, it expects something like:

```
<ul>
  <li class="tab default" data-tab="tab1">The content for this tab will be open by default</li>
  <li class="tab" data-tab="tab2">Second</li>
  <li class="tab" data-tab="tab3">Third</li>
</ul>

<ul>
  <li class="tabContent" data-tab="tab1">The content for tab 1</li>
  <li class="tabContent" data-tab="tab2">The content for tab 2</li>
  <li class="tabContent" data-tab="tab3">The content for tab 3</li>
</ul>
```

We should also use this little library for the schedule tabs.
