### ISSUE TITLE
Highlighted news on the frontpage

### ISSUE THREAD

**Issue by iunetrecet** [GISAElkartea/amv2#133]

**Comment by unaizalakain** [comment]
With these changes, the admins can select a news podcast to be featured, which will make it appear first in every news podcast listing.

I think the simplest thing to do is to always highlight the first news podcast on the frontpage, even if the user hasn't explicitly flag one as featured. To do this, inside the loop on the frontpage that iterates over all news podcast, you could add the following:

```
{% for newspodcast in … %}
{% if forloop.first %}
Do the featured thing
{% endif %}
{% endfor %}
```
