### ISSUE TITLE
In the archive search results, the radio's names aren't links

### ISSUE THREAD

**Issue by iunetrecet** [GISAElkartea/amv2#151]

**Comment by unaizalakain** [comment]
All the searches I made yield results with linked titles, any idea about how could I reproduce the bug?

**Comment by iunetrecet** [comment]
Search for Antxetamedia

**Comment by iunetrecet** [comment]
It's not fixed

**Comment by unaizalakain** [comment]
Ups, sorry! I think now it is.

**Comment by iunetrecet** [comment]
I don't think so

**Comment by iunetrecet** [comment]
Oh! Sorry, you are right!
