### ISSUE TITLE
Add radio show images in the radio show search page

### ISSUE THREAD

**Issue by unaizalakain** [GISAElkartea/amv2#215]

**Comment by iunetrecet** [comment]
Radio show listeko irratiak alfabetikoki ordenatuak egon beharko lirateke, baina ez letrako lista bereizi batean

**Comment by unaizalakain** [comment]
Zergatik? Oso arraroa geldituko zen letraz multzokatuta egongo balira eta bakoitzak irudi bat edukiko balu?

**Comment by iunetrecet** [comment]
Orain lista bakoitzak askozez leku gehiago hartuko luke, eta letren bitartez multzokatuta, lista bukagagabea izango litzake

**Comment by unaizalakain** [comment]
Done! The list is flat now

**Comment by unaizalakain** [comment]
The javascript filtering is broken
