### ISSUE TITLE
Update Antxeta Irratia's logo in the footer

### ISSUE THREAD

**Issue by unaizalakain** [GISAElkartea/amv2#218]

**Comment by iunetrecet** [comment]
Web orri berriko logoa edo euskal irratietako logoa duena?

**Comment by unaizalakain** [comment]
Ez dakit nun eskuratu daitekeen, baina Antxeta Irratiarena, ez Euskal Irratiena.

**Comment by iunetrecet** [comment]
Baina orain Euskal Irratien logoa duena erabiltzen dute Antxeta Irratirako

**Comment by iunetrecet** [comment]
Orain lista bakoitzak askozez leku gehiago hartuko luke, eta letren bitartez multzokatuta, lista bukagagabea izango litzake

**Comment by unaizalakain** [comment]
>Orain lista bakoitzak askozez leku gehiago hartuko luke, eta letren 
>bitartez multzokatuta, lista bukagagabea izango litzake

Ba bai… ok, ba multzokatzearena kenduko dut

-- 
unai
4B3F 515D 76AD A88F A8B5 247B F1DB 723A 779D D1F7
