### ISSUE TITLE
Only show blob list table when a blob exists

### ISSUE THREAD

**Issue by iunetrecet** [GISAElkartea/amv2#229]

**Comment by iunetrecet** [comment]
Ez dakit ze if jarri behar diodan :(

**Comment by unaizalakain** [comment]
>Ez dakit ze if jarri behar diodan :(

Blob zerrenda objetu bateri erlazionatua dago (`newspodcast`, 
`radiopodcast`, `projectpodcast`, dena delakoa). Objetu horretatik blob 
zerrendara `newspodcast.blob_set` bezala iritsi daiteke. Blob zerrenda 
hortan `exists()` metodoak datubaseari ea blob-in dagoen edo ez 
galdetuko dio. Djangoren templateetan metodoak deitzerakoan parentesirik 
jartzen ez denez, hola geldituko zen: `{% if 
radiopodcast.blob_set.exists %}`.

-- 
unai
4B3F 515D 76AD A88F A8B5 247B F1DB 723A 779D D1F7
