### ISSUE TITLE
Aside form label active and inactive with a click

### ISSUE THREAD

**Issue by iunetrecet** [GISAElkartea/amv2#33]

**Comment by unaizalakain** [comment]
I think the checkboxes inside the filter are (de)activated every time you click inside the label they are in. So for example, suppose you have the following:

```
<label for_id="something_unique">
  <input type="checkbox" id="something_unique" checked … />
  Some things in here, it doesn't matter.
</label>
```

Every time you click on something that's inside the label (for example, on the text) the checkbox *should* toggle state.

**Comment by unaizalakain** [comment]
I think the checkboxes inside the filter are (de)activated every time you click inside the label they are in. So for example, suppose you have the following:

```
<label for_id="something_unique">
  <input type="checkbox" id="something_unique" checked … />
  Some things in here, it doesn't matter.
</label>
```

Every time you click on something that's inside the label (for example, on the text) the checkbox *should* toggle state.

**Comment by iunetrecet** [comment]
No, I think that that works only when you click in the checkbox.

**Comment by unaizalakain** [comment]
https://stackoverflow.com/questions/6293588/how-to-create-an-html-checkbox-with-a-clickable-label

See first response and the demo in there.

**Comment by unaizalakain** [comment]
The checkboxes' label has now a `checked` class depending on if the checkbox is checked or not.

**Comment by iunetrecet** [comment]
The label checked doesn't appear in the radio list

**Comment by unaizalakain** [comment]
The checkboxes in the radio show list page now are toggled by the user events and the radio shows are filtered depending on them.
